//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomantiqueX.Engine.Graphics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StandartSemantics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StandartSemantics() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RomantiqueX.Engine.Graphics.StandartSemantics", typeof(StandartSemantics).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COLORLAYERSTOBLEND.
        /// </summary>
        internal static string ColorLayersToBlend {
            get {
                return ResourceManager.GetString("ColorLayersToBlend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPTH.
        /// </summary>
        internal static string DepthTextureArrayPrefix {
            get {
                return ResourceManager.GetString("DepthTextureArrayPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELAPSEDTIME.
        /// </summary>
        internal static string ElapsedTime {
            get {
                return ResourceManager.GetString("ElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAYERCOUNT.
        /// </summary>
        internal static string LayerCount {
            get {
                return ResourceManager.GetString("LayerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREVIOUSLAYERDEPTHTEXTURE.
        /// </summary>
        internal static string PreviousLayerDepthTexture {
            get {
                return ResourceManager.GetString("PreviousLayerDepthTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROJECTIONMATRIX.
        /// </summary>
        internal static string ProjectionMatrix {
            get {
                return ResourceManager.GetString("ProjectionMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEXTUREARRAY.
        /// </summary>
        internal static string TextureArrayPostfix {
            get {
                return ResourceManager.GetString("TextureArrayPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTALTIME.
        /// </summary>
        internal static string TotalTime {
            get {
                return ResourceManager.GetString("TotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEWMATRIX.
        /// </summary>
        internal static string ViewMatrix {
            get {
                return ResourceManager.GetString("ViewMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEWPROJECTIONMATRIX.
        /// </summary>
        internal static string ViewProjectionMatrix {
            get {
                return ResourceManager.GetString("ViewProjectionMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORLDMATRIX.
        /// </summary>
        internal static string WorldMatrix {
            get {
                return ResourceManager.GetString("WorldMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORLDVIEWMATRIX.
        /// </summary>
        internal static string WorldViewMatrix {
            get {
                return ResourceManager.GetString("WorldViewMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORLDVIEWPROJECTIONMATRIX.
        /// </summary>
        internal static string WorldViewProjectionMatrix {
            get {
                return ResourceManager.GetString("WorldViewProjectionMatrix", resourceCulture);
            }
        }
    }
}
